version: "3"
services:
  starknet-node:
    image: eqlabs/pathfinder:latest
    user: root
    restart: unless-stopped
    environment:
      - RUST_LOG=info
    env_file:
      - pathfinder-var.env
    volumes:
      - ./pathfinder:/usr/share/pathfinder/data
    ports:
      - 9545:9545

    healthcheck:
     test: curl --fail http://localhost || exit 1
     interval: 60s
     retries: 5
     start_period: 20s
     timeout: 10s
