---
# tasks file for grafana
 
- name: Update package libfontconfig1
  become: true
  become_method: sudo
  become_user: root
  apt:
    name:  libfontconfig1
    state: present

- name: Get Grafana deb
  ansible.builtin.get_url:
    url: "https://dl.grafana.com/oss/release/grafana_7.0.3_amd64.deb"
    dest: "./grafana_7.0.3_amd64.deb"
    mode: "0644"

- name: installed Grafana
  become: true
  ansible.builtin.command: dpkg -i grafana_7.0.3_amd64.deb
  register: deb_check
 
- name: Make sure grafana service is enabled and running
  become: true
  service:
    name: grafana-server
    enabled: yes
    state: started