---
# tasks file for grafana
 
- name: Update package libfontconfig1
  apt:
    name:  libfontconfig1
    state: fixed

- name: Get Grafana deb
  ansible.builtin.get_url:
    url: "https://dl.grafana.com/oss/release/grafana_7.0.3_amd64.deb"
    dest: "./grafana_7.0.3_amd64.deb"
    mode: "0644"

- name: installed Grafana
  ansible.builtin.command: dpkg -i grafana_7.0.3_amd64.deb
  register: deb_check

- name: start and enable grafana-server
  systemd:
    name: grafana-server.service
    state: started
    enabled: true
  
