- name: install utils
  hosts: node1
  become: yes
  gather_facts: false
  
  roles: 
    - docker_install
    - container_pathfinder
    - prometheus-exporter

- name: install monitoring
  hosts: monitoring
  become: yes
  gather_facts: false

  roles: 
    - grafana
    - prometheus
    - loki
    
